name: Auto Update trial playlists

      - name: Run update script
        run: |
          bash scripts/update.sh

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add thomas.m3u duncan.m3u
          git commit -m "Auto-update playlists" || echo "No changes"
          git push
