name: Bang TV Sports Daily

on:
  schedule:
    # 10 PM NZ local time (runs at 10 AM UTC)
    - cron: "0 10 * * *"
  workflow_dispatch:
    inputs:
      force:
        description: "Force post schedule?"
        required: false
        default: "no"

concurrency:
  group: bangtv-daily-scraper
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - id: checkout
        uses: actions/checkout@v4

      - id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - id: install-deps
        run: pip install --no-cache-dir requests beautifulsoup4
        shell: bash

      - id: run-scraper
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: python -u bangtv/scraper.py ${{ github.event.inputs.force == 'yes' && 'force' || '' }}
        shell: bash
        continue-on-error: true

      - id: commit-lastjson
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update last.json"
          file_pattern: bangtv/last.json
          skip_dirty_check: false
