name: Generate EPG (WebGrabPlus V5.5)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Microsoft package feed + DOTNET 8
        run: |
          sudo apt-get update
          sudo apt-get install -y wget apt-transport-https software-properties-common
          wget https://packages.microsoft.com/config/ubuntu/24.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
          sudo dpkg -i packages-microsoft-prod.deb
          sudo apt-get update
          sudo apt-get install -y dotnet-runtime-8.0

      - name: Verify DOTNET
        run: dotnet --version

      - name: Download WebGrab+Plus V5.5
        run: |
          wget https://webgrabplus.com/sites/default/files/download/SW/V5.5.0/WebGrabPlus_5.5_install.tar.gz
          tar -zxvf WebGrabPlus_5.5_install.tar.gz -C $HOME

      - name: Install WebGrab+Plus
        run: |
          cd $HOME/.wg++
          ./install.sh

      - name: Copy config + siteini
        run: |
          cp iptv/WebGrab++.config.xml $HOME/.wg++/
          cp -r iptv/siteini.pack $HOME/.wg++/

      - name: Run WebGrab+Plus
        run: |
          cd $HOME/.wg++
          ./run.net.sh

      - name: Save EPG to /iptv/epg/
        run: |
          cp $HOME/.wg++/guide.xml iptv/epg/epg.xml
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add iptv/epg/epg.xml
          git commit -m "EPG update"
          git push
