name: Fetch Movies Data

on:
  schedule:
    - cron: '0 */4 * * *'  # Runs every 4 hours
  workflow_dispatch:  # Allows manual triggering

jobs:
  fetch-movies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch 5000 movies from TMDB
        env:
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
        run: |
          mkdir -p movies_data

          # Initialize the JSON array
          echo '{"results":[' > movies_data/movies.json

          # Loop through pages to fetch up to 5000 movies (20 per page, up to 250 pages)
          for page in $(seq 1 250); do
            response=$(curl -s "https://api.themoviedb.org/3/discover/movie?api_key=$TMDB_API_KEY&page=$page")

            # Extract the results array from each page response and append it
            movies=$(echo "$response" | jq -c '.results[]')
            for movie in $movies; do
              echo "$movie," >> movies_data/movies.json
            done
          done

          # Remove the trailing comma and close the JSON array
          sed -i '$ s/,$//' movies_data/movies.json
          echo ']}' >> movies_data/movies.json

      - name: Commit and push movie data
        run: |
          git config user.name "tdbnz-coding"
          git config user.email "bise@smartbusiness.me"
          git add movies_data/movies.json
          git commit -m "Update movies data with 5000 movies"
          git push origin main