name: Fetch Movies Data

on:
  schedule:
    - cron: '0 */4 * * *'  # Runs every 4 hours
  workflow_dispatch:  # Allows manual triggering

jobs:
  fetch-movies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch 5000 movies from TMDB
        env:
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
        run: |
          mkdir -p movies_data

          # Initialize the JSON structure
          echo '{"results":[' > movies_data/movies.json

          # Loop through up to 250 pages (5000 movies total)
          for page in $(seq 1 250); do
            response=$(curl -s "https://api.themoviedb.org/3/discover/movie?api_key=$TMDB_API_KEY&page=$page" | jq '.results[]')
            
            # Append each movie as a valid JSON object
            echo "$response," >> movies_data/movies.json
          done

          # Remove trailing comma from the last entry
          sed -i '$ s/,$//' movies_data/movies.json

          # Close the JSON structure
          echo ']}' >> movies_data/movies.json

      - name: Validate JSON File
        run: |
          cat movies_data/movies.json | jq . > /dev/null || { echo "Invalid JSON"; exit 1; }

      - name: Commit and push movie data
        run: |
          git config user.name "tdbnz-coding"
          git config user.email "bise@smartbusiness.me"
          git add movies_data/movies.json
          git commit -m "Update movies data with 5000 movies"
          git push origin main