name: Fetch Movies Data Beta

on:
  schedule:
    - cron: '0 */4 * * *' # Runs every 4 hours
  workflow_dispatch: # Allow manual triggering

jobs:
  fetch-movies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch movies
        env:
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
        run: |
          mkdir -p movies_data
          echo '{"results":[' > movies_data/moviesbeta.json

          for page in $(seq 1 250); do
            movie_response=$(curl -s "https://api.themoviedb.org/3/discover/movie?api_key=$TMDB_API_KEY&page=$page")
            if echo "$movie_response" | jq empty > /dev/null 2>&1; then
              echo "$movie_response" | jq -c '.results[]' >> movies_data/tmp_movies.json
            fi
          done

          jq -s '{results: .}' movies_data/tmp_movies.json > movies_data/moviesbeta.json
          rm -f movies_data/tmp_movies.json

      - name: Commit and push movie data
        run: |
          git config user.name "tdbnz-coding"
          git config user.email "bise@smartbusiness.me"
          git add movies_data/moviesbeta.json
          git commit -m "Update movies data"
          git push origin main
