name: KFC Promo Scraper

on:
  schedule:
    - cron: '11 11 * * *'  # Daily at 00:11 NZST/NZDT
  workflow_dispatch:

jobs:
  update-promos:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies from kfc folder
        run: pip install -r kfc/requirements.txt

      - name: Run promo scraper from kfc folder
        run: python kfc/promo_scraper.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add kfc/index.html
          git commit -m "🔄 Auto-update KFC promo codes"
          git push
