name: KFC Promo Scraper

on:
  schedule:
    - cron: '11 11 * * *'  # Midnight NZ time (11:11 UTC)
  workflow_dispatch:

jobs:
  update-promos:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies from foodgenerator/kfc
        run: pip install -r foodgenerator/kfc/requirements.txt

      - name: Run scraper
        run: python foodgenerator/kfc/promo_scraper.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add foodgenerator/kfc/index.html
          git commit -m "🔄 Auto-update KFC promo codes"
          git push
