name: KFC Promo Scraper

on:
  schedule:
    # Run every day at midnight New Zealand time (UTC+12 or UTC+13 daylight)
    - cron: '11 11 * * *'  # 11:11 UTC = 00:11 NZST/NZDT (safe for GitHub delay)
  workflow_dispatch:

jobs:
  update-promos:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run promo scraper
        run: python promo_scraper.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add index.html
          git commit -m "🔄 Auto-update KFC promo codes"
          git push
